config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "homes#index"

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :templates do
    member do
      post :sample_template
      post :upload_image
    end

    collection do
      post :sample_template
      post :upload_image
    end
  end

  resources :companies do
    resources :memberships, only: [:create, :destroy] do
      collection do
        post :add_owner
      end
    end

    resources :projects do
      post :sample_document, on: :member

      resources :documents do
        member do
          get  :document_images
          post :upload_image
        end

        collection do
          post :create_from_template
        end
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  authenticate :user, lambda { |u| u.admin? || u.email == 'web.dev.adk@gmail.com' } do
    mount PgHero::Engine, at: "pghero"
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/templates/_form.html.erb
<%= form_with model: [template],
              local: true,
              data: {
                controller: "template-editor",
                current_language: I18n.locale,
                template_editor_upload_url: upload_image_template_path(template)
              } do |form| %>
  <div class="form-group mb-3">
    <%= render 'shared/errors', resource: template %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :title, t('title'), class: 'form-label' %>
    <%= form.text_field :title, class: "form-control", placeholder: t('title') %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :content, t('content'), class: 'form-label' %>
    <%= form.text_area :content, class: "form-control", data: { template_editor_target: "content" }, hidden: true %>
    <%= form.hidden_field :content, id: "template_content_hidden", data: { template_editor_target: "hiddenContent" } %>
  </div>
  <div class="form-group d-grid mb-3">
    <%= form.submit I18n.t('.save'), class: "btn btn-success" %>
  </div>
<% end %>

app/views/templates/_nav.html.erb
<nav id="sidebar" class="data-bs-theme col-md-3 col-lg-2 d-md-block sidebar collapse">
  <div class="position-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link #{'active' if current_page?(root_path)}", aria: { current: "page" } do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
            <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
            <polyline points="9 22 9 12 15 12 15 22"></polyline>
          </svg>
          <span class="ms-2"><%= I18n.t('.dashboard') %></span>
        <% end %>
      </li>
      <hr>
      <li class="nav-item">
        <%= link_to companies_path, class: "nav-link #{'active' if current_page?(companies_path)}" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-buildings" viewBox="0 0 16 16">
            <path d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022M6 8.694 1 10.36V15h5zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5z"/>
            <path d="M2 11h1v1H2zm2 0h1v1H4zm-2 2h1v1H2zm2 0h1v1H4zm4-4h1v1H8zm2 0h1v1h-1zm-2 2h1v1H8zm2 0h1v1h-1zm2-2h1v1h-1zm0 2h1v1h-1zM8 7h1v1H8zm2 0h1v1h-1zm2 0h1v1h-1zM8 5h1v1H8zm2 0h1v1h-1zm2 0h1v1h-1zm0-2h1v1h-1z"/>
          </svg>
          <span class="ms-2"><%= I18n.t('.companies') %></span>
        <% end %>
      </li>
      <hr>
      <li class="nav-item">
        <%= link_to templates_path, class: "nav-link #{'active' if @template || current_page?(templates_path) }" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-file-earmark-richtext" viewBox="0 0 16 16">
            <path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/>
            <path d="M4.5 12.5A.5.5 0 0 1 5 12h3a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5m0-2A.5.5 0 0 1 5 10h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5m1.639-3.708 1.33.886 1.854-1.855a.25.25 0 0 1 .289-.047l1.888.974V8.5a.5.5 0 0 1-.5.5H5a.5.5 0 0 1-.5-.5V8s1.54-1.274 1.639-1.208M6.25 6a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5"/>
          </svg>
          <span class="ms-2"><%= I18n.t('.templates') %></span>
        <% end %>
      </li>
      <hr>
      <%= render "shared/link_tutorial" %>
    </ul>
  </div>
</nav>

app/views/templates/_template.html.erb
<tr>
  <td><%= template.title %></td>
  <td><%= template.updated_at %></td>
  <td class="text-end">
    <%= button_to create_from_template_company_project_documents_path(
          template_id: template.id,
          company_id: company.id,
          project_id: project.id),
          method: :post,
          class: 'btn btn-sm btn-outline-success' do %>
      <span class="ms-2"><%= t('.create_document_with_template') %></span>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-copy" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M4 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 5a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1h1v1a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h1v1z"/>
      </svg>
    <% end %>
  </td>
</tr>

app/views/templates/_template2.html.erb
<div class="col-12 col-md-6 col-lg-3">
  <div class="card">
    <div class="card-header"><%= template.updated_at %></div>
    <div class="card-body">
      <h5 class="card-title"><%= template.title.truncate(20) %></h5>
      <%= link_to template_path(template), class: "btn btn-sm btn-outline-success" do %>
        <span class="ms-2"><%= I18n.t('.open') %></span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8"/>
        </svg>
      <% end %>
    </div>
  </div>
</div>

app/views/templates/_template3.html.erb
<div class="col-12 col-md-6 col-lg-3">
  <div class="card">
    <div class="card-header"><%= template.updated_at %></div>
    <div class="card-body">
      <h5 class="card-title"><%= template.title.truncate(20) %></h5>
      <%= link_to template_path(template), class: "btn btn-sm btn-outline-success" do %>
        <span class="ms-2"><%= I18n.t('.open') %></span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8"/>
        </svg>
      <% end %>
    </div>
  </div>
</div>

app/views/templates/edit.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="p-3">
      <h1><%= t('edit') %></h1>
      <%= render "form", template: @template %>
    </div>
    <div class="btn-group pt-3">
      <%= link_to templates_path, class: "btn btn-secondary", title: t('back') do %>
        <i class="bi bi-arrow-left-circle-fill"></i>
      <% end %>
    </div>
  </main>
</div>

app/views/templates/index.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 my-4">
    <%= render 'layouts/breadcrumbs' %>
    <h1><%= t('all_list') %></h1>
    <div class="table-responsive" data-controller="datatables" data-datatables-language-value="<%= I18n.locale %>">
      <table class="table table-hover" data-datatables-target="table">
        <thead>
          <tr>
            <th scope="col"><%= ::Template.human_attribute_name(:title) %></th>
            <th scope="col"><%= ::Template.human_attribute_name(:updated_at) %></th>
            <th scope="col" class="text-end"><%= I18n.t('.actions') %></th>
          </tr>
        </thead>
        <tbody>
          <%= render collection: @templates, partial: 'templates/template2', as: :template %>
        </tbody>
      </table>
    </div>
    <% if can?(:create, Template) %>
      <div class="btn-group mt-3">
        <%= button_to t('new'), sample_template_templates_path, method: :post, class: "btn btn-primary" %>
      </div>
    <% end %>
  </main>
</div>

app/views/templates/new.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="p-3">
      <h1><%= t('new') %></h1>
      <%= render "form", template: @template %>
    </div>
    <div class="btn-group pt-3">
      <%= link_to templates_path, class: "btn btn-secondary", title: t('back') do %>
        <i class="bi bi-arrow-left-circle-fill"></i>
      <% end %>
    </div>
  </main>
</div>

app/views/templates/show.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="p-3">
      <h1><%= @template.title %></h1>
      <div class="sun-editor-editable border rounded overflow-y-scroll h-650 p-5"><%= Sanitize.fragment(@template.content) %></div>
    </div>
    <div class="btn-group pt-3">
      <% if can?(:destroy, @template) && can?(:update, @template) %>
        <%= button_to template_path(@template),
            method: :delete,
            data: { turbo_confirm: t('are_you_sure') },
            class: "btn btn-danger",
            title: t('destroy') do %>
          <i class="bi bi-trash3-fill"></i>
        <% end %>
        <%= link_to edit_template_path(@template), class: "btn btn-warning", title: t('edit') do %>
          <i class="bi bi-pencil-fill"></i>
        <% end %>
        <%= link_to templates_path, class: "btn btn-secondary", title: t('back') do %>
          <i class="bi bi-arrow-left-circle-fill"></i>
        <% end %>
      <% else %>
        <%= link_to templates_path, class: "btn btn-secondary", title: t('back') do %>
          <i class="bi bi-arrow-left-circle-fill"></i>
        <% end %>
      <% end %>
    </div>
  </main>
</div>