config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "homes#index"

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :templates do
    member do
      post :sample_template
      post :upload_image
    end

    collection do
      post :sample_template
      post :upload_image
    end
  end

  resources :companies do
    resources :memberships, only: [:create, :destroy] do
      collection do
        post :add_owner
      end
    end

    resources :projects do
      post :sample_document, on: :member

      resources :documents do
        member do
          get  :document_images
          post :upload_image
        end

        collection do
          post :create_from_template
        end
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  authenticate :user, lambda { |u| u.admin? || u.email == 'web.dev.adk@gmail.com' } do
    mount PgHero::Engine, at: "pghero"
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :template, optional: true
  belongs_to :company, optional: true
  belongs_to :project, optional: true

  has_many :document_images, dependent: :destroy
  accepts_nested_attributes_for :document_images, allow_destroy: true

  validates :title, presence: true, uniqueness: true
  validates :content, presence: true

  scope :latest, ->(limit = 10) { order(created_at: :desc).limit(limit) }

  def author_of_document?(document, user)
    document.user_id == user.id
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_company,      only:  [:upload_image, :create_from_template, :index, :show, :edit, :update, :new, :create, :destroy]
  before_action :set_project,      only:  [:upload_image, :create_from_template, :index, :show, :edit, :update, :new, :create, :destroy]
  before_action :set_document,     only:  [:show, :edit, :update, :destroy]
  before_action :set_template,     only:  [:create_from_template]
  before_action :check_membership, only:  [:show, :edit, :update, :destroy]

  protect_from_forgery except: :upload_image

  load_and_authorize_resource

  def create_from_template
    if @company.member?(current_user)
      unique_title = @template.title
      count = 1
      while Document.exists?(title: unique_title)
        unique_title = "#{@template.title} (#{count})"
        count += 1
      end

      @document = Document.new(
        title: unique_title,
        content: @template.content,
        template: @template,
        user: current_user,
        company: @company,
        project: @project
      )

      if @document.save
        redirect_to company_project_document_path(@document.company, @document.project, @document), notice: I18n.t('.created')
      else
        redirect_to company_project_documents_path(@document.company, @document.project), alert: I18n.t('.not_created')
      end
    else
      redirect_to root_path, alert: I18n.t('.first_create_a_company')
    end
  end

  def index
    @breadcrumbs = [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
      { name: "#{I18n.t('.companies')}", url: companies_path },
      { name: "#{@company.name}", url: company_path(@company) },
      { name: "#{I18n.t('.projects')}", url: company_projects_path(@company) },
      { name: "#{@project.title}", url: company_project_path(@company, @project) },
      { name: "#{I18n.t('.documents')}", current: true }
    ]

    @templates = Template.all
    @project_documents = @project.documents.includes(:project)
  end

  def show
    @document.content = @document.content&.gsub("<h1 class='cn'></h1>", "<h1>#{@document.company.name}</h1>")
    @document.save

    @breadcrumbs = [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
      { name: "#{I18n.t('.companies')}", url: companies_path },
      { name: "#{@company.name}", url: company_path(@company) },
      { name: "#{I18n.t('.projects')}", url: company_projects_path(@company) },
      { name: "#{@project.title}", url: company_project_path(@company, @project) },
      { name: "#{I18n.t('.documents')}", url: company_project_documents_path(@company, @project) },
      { name: "#{@document.title.truncate(70)}", current: true },
    ]
  end

  def new
    @breadcrumbs = [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
      { name: "#{I18n.t('.companies')}", url: companies_path },
      { name: "#{@company.name}", url: company_path(@company) },
      { name: "#{I18n.t('.projects')}", url: company_projects_path(@company) },
      { name: "#{@project.title}", url: company_project_path(@company, @project) },
      { name: "#{I18n.t('.documents')}", url: company_project_documents_path(@company, @project) },
      { name: "#{I18n.t('.new')}", current: true }
    ]

    @document = @project.documents.new
  end

  def create
    @document = @project.documents.new(document_params)
    @document.user = current_user
    @document.company = @company

    if @document.save
      @breadcrumbs = [
        { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
        { name: "#{I18n.t('.companies')}", url: companies_path },
        { name: "#{@company.name}", url: company_path(@company) },
        { name: "#{I18n.t('.projects')}", url: company_projects_path(@company) },
        { name: "#{@project.title}", url: company_project_path(@company, @project) },
        { name: "#{I18n.t('.documents')}", current: true }
      ]

      redirect_to [@company, @project, @document], notice: I18n.t('.created')
    else
      @breadcrumbs = [
        { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
        { name: "#{I18n.t('.companies')}", url: companies_path },
        { name: "#{@company.name}", url: company_path(@company) },
        { name: "#{I18n.t('.projects')}", url: company_projects_path(@company) },
        { name: "#{@project.title}", url: company_project_path(@company, @project) },
        { name: "#{I18n.t('.documents')}", current: true }
      ]

      redirect_to new_company_project_document_path(@company, @project), alert: I18n.t('.not_created'), status: :unprocessable_entity
    end
  end

  def edit
    @breadcrumbs = [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
      { name: "#{I18n.t('.companies')}", url: companies_path },
      { name: "#{@company.name}", url: company_path(@company) },
      { name: "#{I18n.t('.projects')}", url: company_projects_path(@company) },
      { name: "#{@project.title}", url: company_project_path(@company, @project) },
      { name: "#{I18n.t('.documents')}", url: company_project_documents_path(@company, @project) },
      { name: "#{@document.title}", url: company_project_document_path(@company, @project, @document) },
      { name: "#{I18n.t('.edit')}", current: true },
    ]
  end

  def update
    if @document.update(document_params)
      @breadcrumbs = [
        { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
        { name: "#{I18n.t('.companies')}", url: companies_path },
        { name: "#{@company.name}", url: company_path(@company) },
        { name: "#{I18n.t('.projects')}", url: company_projects_path(@company) },
        { name: "#{@project.title}", url: company_project_path(@company, @project) },
        { name: "#{I18n.t('.documents')}", current: true }
      ]

      redirect_to company_project_document_path(@company, @project, @document), notice: I18n.t('.updated')
    else
      @breadcrumbs = [
        { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
        { name: "#{I18n.t('.companies')}", url: companies_path },
        { name: "#{@company.name}", url: company_path(@company) },
        { name: "#{I18n.t('.projects')}", url: company_projects_path(@company) },
        { name: "#{@project.title}", url: company_project_path(@company, @project) },
        { name: "#{I18n.t('.documents')}", current: true }
      ]

      render :edit, alert: I18n.t('.not_updated'), status: :unprocessable_entity
    end
  end

  def destroy
    @document.destroy
    redirect_to company_project_documents_path(@company, @project), notice: I18n.t('.destroyed')
  end

  def upload_image
    document = Document.find_by(id: params[:id])

    document_image = document.document_images.build
    document_image.image.attach(params["file-0"])

    if document_image.save
      render json: {
        success: true,
        url: url_for(document_image.image),
        message: I18n.t('.uploaded')
      }
    else
      render json: {
        success: false,
        message: I18n.t('.not_uploaded')
      }, status: :unprocessable_entity
    end
  end

  private

    def set_template
      @template = Template.find_by_id(params[:template_id])
    end

    def set_document
      @document = Document.find_by_id(params[:id])
    end

    def set_company
      @company = Company.find_by_id(params[:company_id])
    end

    def set_project
      @project = Project.find_by_id(params[:project_id])
    end

    def check_membership
      unless current_user.companies.exists?(id: @document.company_id) || current_user.admin?
        redirect_to root_path, alert: I18n.t('.not_authorized')
      end
    end

    def document_params
      params.require(:document).permit(:title, :content, document_images_attributes: [:image])
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<tr>
  <td><%= document.title.truncate(50) %></td>
  <td><%= document.updated_at %></td>
  <td class="text-end">
    <% if document.company && document.company.memberships.exists?(user_id: current_user.id, role: Membership.roles[:owner]) %>
      <%= link_to company_project_document_path(@company, @project, document),
          class: "position-relative btn btn-sm btn-outline-danger" do %>
        <span class="ms-2" title="Reading document..."><%= t('.open') %></span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8"/>
        </svg>
        <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle"></span>
      <% end %>
    <% else %>
      <%= link_to company_project_document_path(@company, @project, document),
          class: "position-relative btn btn-sm btn-outline-success" do %>
        <span class="ms-2" title="Reading document..."><%= t('.open') %></span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8"/>
        </svg>
        <span class="position-absolute top-0 start-100 translate-middle p-2 bg-success border border-light rounded-circle"></span>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/documents/_form.html.erb
<%= form_with model: [company, project, document],
              local: true,
              data: {
                controller: "document-editor",
                current_language: I18n.locale,
                document_editor_upload_url: upload_image_company_project_document_path(company, project, document)
              } do |form| %>
  <div class="form-group mb-3">
    <%= render 'shared/errors', resource: document %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :title, t('title'), class: 'form-label' %>
    <%= form.text_field :title, class: "form-control", placeholder: t('title') %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :content, t('content'), class: 'form-label' %>
    <%= form.text_area :content, class: "form-control",
                                 data: { document_editor_target: "content"},
                                 hidden: true %>
    <%= form.hidden_field :content, id: "document_content_hidden", data: { document_editor_target: "hiddenContent" } %>
  </div>
  <div class="form-group d-grid mb-3">
    <%= form.submit I18n.t('.save'), class: "btn btn-success" %>
  </div>
<% end %>

app/views/documents/_nav.html.erb
<nav id="sidebar" class="data-bs-theme col-md-3 col-lg-2 d-md-block sidebar collapse">
  <div class="position-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to company_project_path(@company, @project), class: "nav-link #{'active' if current_page?(company_project_path(@company, @project)) || current_page?(edit_company_project_path(@company, @project))}", aria: { current: "page" } do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cast" viewBox="0 0 16 16">
            <path d="m7.646 9.354-3.792 3.792a.5.5 0 0 0 .353.854h7.586a.5.5 0 0 0 .354-.854L8.354 9.354a.5.5 0 0 0-.708 0"/>
            <path d="M11.414 11H14.5a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.5-.5h-13a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5h3.086l-1 1H1.5A1.5 1.5 0 0 1 0 10.5v-7A1.5 1.5 0 0 1 1.5 2h13A1.5 1.5 0 0 1 16 3.5v7a1.5 1.5 0 0 1-1.5 1.5h-2.086z"/>
          </svg>
          <span class="ms-2"><%= @project.title %></span>
        <% end %>
      </li>
      <hr>
      <li class="nav-item">
        <%= link_to company_project_documents_path(@company, @project), class: "nav-link #{'active' if project_documents_active?(@company, @project, @document)}" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
            <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/>
            <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
          </svg>
          <span class="ms-2"><%= I18n.t('.documents') %></span>
        <% end %>
      </li>
      <hr>
      <%= render "shared/link_tutorial" %>
    </ul>
  </div>
</nav>

app/views/documents/edit.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="p-3">
      <h1><%= t('edit') %></h1>
      <%= render "form", company: @company, project: @project, document: @document %>
    </div>
    <div class="btn-group pt-3">
      <%= link_to company_project_document_path(@company, @project, @document), class: "btn btn-secondary", title: t('back') do %>
        <i class="bi bi-arrow-left-circle-fill"></i>
      <% end %>
    </div>
  </main>
</div>

app/views/documents/index.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 mt-4">
    <%= render 'layouts/breadcrumbs' %>
    <h1><%= t('all_list') %>
      <small>
        <% if can?(:create, Document) && @project.documents.empty? %>
          <div class="btn-group">
            <%= button_to "+", sample_document_company_project_path(@company, @project),
              method: :post,
              class: "btn btn-sm btn-outline-primary rounded-pill mb-2" %>
          </div>
        <% end %>
      </small>
    </h1>
    <ul class="nav nav-fill nav-tabs" id="pills-tab" role="tablist">
      <!-- Вкладки для проектов -->
      <% @project_documents.group_by(&:project).each_with_index do |(project, docs), index| %>
        <li class="nav-item" role="presentation">
          <a class="data-bs-theme text-uppercase fw-bold nav-link <%= 'active' if index == 0 %>" id="pills-project-<%= project.id %>-tab" data-bs-toggle="tab" data-bs-target="#pills-project-<%= project.id %>" role="tab" aria-controls="pills-project-<%= project.id %>" aria-selected="<%= index == 0 %>">
            <%= project.title %>
          </a>
        </li>
      <% end %>
      <!-- Вкладки для проектов -->

      <!-- Вкладка для шаблонов -->
      <li class="nav-item" role="presentation">
        <a class="data-bs-theme text-uppercase fw-bold nav-link" id="pills-templates-tab" data-bs-toggle="tab" data-bs-target="#pills-templates" role="tab" aria-controls="pills-templates" aria-selected="false">
          <%= I18n.t('.templates') %>
        </a>
      </li>
      <!-- Вкладка для шаблонов -->
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <!-- Содержимое для проектов -->
      <% @project_documents.group_by(&:project).each do |project, docs| %>
        <div class="tab-pane fade <%= 'show active' if docs.first == @project_documents.first %>" id="pills-project-<%= project.id %>" role="tabpanel" aria-labelledby="pills-project-<%= project.id %>-tab" tabindex="0">
          <div class="table-responsive" data-controller="datatables" data-datatables-language-value="<%= I18n.locale %>">
            <table class="table table-hover" data-datatables-target="table">
              <thead>
                <tr>
                  <th scope="col"><%= I18n.t('.title') %></th>
                  <th scope="col"><%= I18n.t('activerecord.attributes.document.updated_at') %></th>
                  <th scope="col" class="text-end"><%= I18n.t('.actions') %></th>
                </tr>
              </thead>
              <tbody>
                <%= render collection: docs, partial: 'documents/document', as: :document %>
              </tbody>
            </table>
          </div>

          <% if can?(:create, Document) %>
            <div class="btn-group mt-3">
              <%= button_to t('new'), sample_document_company_project_path(@company, @project),
                  method: :post,
                  class: "btn btn-sm btn-outline-primary",
                  title: "Create document" %>
            </div>
          <% end %>
        </div>
      <% end %>
      <!-- Содержимое для проектов -->

      <!-- Содержимое для шаблонов -->
      <div class="tab-pane fade" id="pills-templates" role="tabpanel" aria-labelledby="pills-templates-tab" tabindex="0">
        <div class="table-responsive" data-controller="datatables" data-datatables-language-value="<%= I18n.locale %>">
          <table class="table table-hover" data-datatables-target="table">
            <thead>
              <tr>
                <th scope="col"><%= I18n.t('.title') %></th>
                <th scope="col"><%= I18n.t('activerecord.attributes.document.updated_at') %></th>
                <th scope="col" class="text-end"><%= I18n.t('.actions') %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: 'templates/template', collection: @templates, as: :template, locals: { company: @company, project: @project } %>
            </tbody>
          </table>
        </div>

        <% if can?(:create, Template) %>
          <div class="btn-group mt-3">
            <%= button_to t('new'), sample_template_templates_path,
                method: :post,
                class: "btn btn-sm btn-outline-primary",
                title: "Create template" %>
          </div>
        <% end %>
      </div>
      <!-- Содержимое для шаблонов -->
  </main>
</div>

app/views/documents/new.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="p-3">
      <h1><%= t('new') %></h1>
      <%= render "form", company: @company, project: @project, document: @document %>
    </div>
    <div class="btn-group pt-3">
      <%= link_to company_project_documents_path(@company, @project), class: "btn btn-secondary", title: t('back') do %>
        <i class="bi bi-arrow-left-circle-fill"></i>
      <% end %>
    </div>
  </main>
</div>

app/views/documents/show.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="p-3">
      <h1><%= @document.title %></h1>
      <div class="sun-editor-editable border rounded overflow-y-scroll h-650 p-5"><%= Sanitize.fragment(@document.content) %></div>
    </div>
    <div class="btn-group pt-3">
      <% if can?(:manage, @document) %>
        <%= button_to company_project_document_path(@company, @project, @document), method: :delete, data: { turbo_confirm: t('are_you_sure') }, class: "btn btn-danger", title: t('destroy') do %>
          <i class="bi bi-trash3-fill"></i>
        <% end %>
        <%= link_to edit_company_project_document_path(@company, @project, @document), class: "btn btn-warning", title: t('edit') do %>
          <i class="bi bi-pencil-fill"></i>
        <% end %>
        <%= link_to company_project_documents_path(@company, @project), class: "btn btn-secondary", title: t('back') do %>
          <i class="bi bi-arrow-left-circle-fill"></i>
        <% end %>
      <% else %>
        <%= link_to company_project_documents_path(@company, @project), class: "btn btn-secondary", title: t('back') do %>
          <i class="bi bi-arrow-left-circle-fill"></i>
        <% end %>
      <% end %>
    </div>
  </main>
</div>