config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "homes#index"

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :templates do
    member do
      post :sample_template
      post :upload_image
    end

    collection do
      post :sample_template
      post :upload_image
    end
  end

  resources :companies do
    resources :memberships, only: [:create, :destroy] do
      collection do
        post :add_owner
      end
    end

    resources :projects do
      post :sample_document, on: :member

      resources :documents do
        member do
          get  :document_images
          post :upload_image
        end

        collection do
          post :create_from_template
        end
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  authenticate :user, lambda { |u| u.admin? || u.email == 'web.dev.adk@gmail.com' } do
    mount PgHero::Engine, at: "pghero"
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :projects, dependent: :destroy

  default_scope { order(created_at: :DESC) }

  validates :name, presence: true, uniqueness: true

  def member?(user)
    memberships.exists?(user_id: user.id)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :create]

  load_and_authorize_resource

  def index
    @breadcrumbs = [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
      { name: "#{I18n.t('.companies')}", current: true }
    ]

    @user_companies = current_user&.companies.includes(:memberships)
    @companies = Company.all.includes(:memberships)
  end

  def show
    @breadcrumbs = [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
      { name: "#{I18n.t('.companies')}", url: companies_path },
      { name: "#{@company.name}", current: true }
    ]
  end

  def new
    @breadcrumbs = [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
      { name: "#{I18n.t('.companies')}", url: companies_path },
      { name: "#{I18n.t('.new')}", current: true }
    ]

    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: I18n.t('.created')
    else
      render :new, alert: I18n.t('.not_created'), status: :unprocessable_entity
    end
  end

  def edit
    @breadcrumbs = [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path },
      { name: "#{I18n.t('.companies')}", url: companies_path },
      { name: "#{@company.name}", url: company_path(@company) },
      { name: "#{I18n.t('.edit')}", current: true }
    ]
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: I18n.t('.updated')
    else
      render :edit, alert: I18n.t('.not_updated'), status: :unprocessable_entity
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_path, notice: I18n.t('.destroyed')
  end

  private

    def check_admin
      redirect_to companies_path, alert: I18n.t('.access_denied') unless current_user.admin?
    end

    def set_company
      @company ||= Company.find_by_id(params[:id])
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/views/companies/_company.html.erb
<% row_class = if admin
                  ''
                elsif company.memberships.owner.exists?(user_id: current_user.id)
                  'table-danger'
                else
                  'table-primary'
                end %>

<tr class="<%= row_class %>" style="cursor: pointer;">
  <td>
    <%= company.name %>
  </td>
  <td><small><%= company.updated_at %></small></td>
  <td>
    <span class="badge bg-primary rounded-pill"><%= company.memberships.count %></span>
  </td>
  <td class="text-end">
    <%= link_to company_path(company), class: "btn btn-sm btn-outline-primary" do %>
      <span class="ms-2" title="<%= I18n.t('.open') %>"><%= I18n.t('.open') %></span>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8"/>
      </svg>
    <% end %>
  </td>
</tr>

app/views/companies/_form.html.erb
<%= form_for(company, html: { class: "form" }) do |f| %>
  <div class="form-group mb-3">
    <%= render "shared/errors", resource: company %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group d-grid">
    <%= f.submit I18n.t('.save'), class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/companies/_nav.html.erb
<nav id="sidebar" class="data-bs-theme col-md-3 col-lg-2 d-md-block sidebar collapse">
  <div class="position-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to company_path(@company), class: "nav-link #{'active' if current_page?(@company) || current_page?(edit_company_path(@company))}" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-buildings" viewBox="0 0 16 16">
            <path d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022M6 8.694 1 10.36V15h5zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5z"/>
            <path d="M2 11h1v1H2zm2 0h1v1H4zm-2 2h1v1H2zm2 0h1v1H4zm4-4h1v1H8zm2 0h1v1h-1zm-2 2h1v1H8zm2 0h1v1h-1zm2-2h1v1h-1zm0 2h1v1h-1zM8 7h1v1H8zm2 0h1v1h-1zm2 0h1v1h-1zM8 5h1v1H8zm2 0h1v1h-1zm2 0h1v1h-1zm0-2h1v1h-1z"/>
          </svg>
          <span class="ms-2"><%= @company.name %></span>
        <% end %>
      </li>
      <hr>
      <li class="nav-item">
        <%= link_to company_projects_path(@company), class: "nav-link #{'active' if current_page?(company_projects_path(@company)) || current_page?(new_company_project_path(@company))}" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cast" viewBox="0 0 16 16">
            <path d="m7.646 9.354-3.792 3.792a.5.5 0 0 0 .353.854h7.586a.5.5 0 0 0 .354-.854L8.354 9.354a.5.5 0 0 0-.708 0"/>
            <path d="M11.414 11H14.5a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.5-.5h-13a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .5.5h3.086l-1 1H1.5A1.5 1.5 0 0 1 0 10.5v-7A1.5 1.5 0 0 1 1.5 2h13A1.5 1.5 0 0 1 16 3.5v7a1.5 1.5 0 0 1-1.5 1.5h-2.086z"/>
          </svg>
          <span class="ms-2"><%= I18n.t('.projects') %></span>
        <% end %>
      </li>
      <hr>
      <%= render "shared/link_tutorial" %>
    </ul>
  </div>
</nav>

app/views/companies/edit.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 my-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="p-3">
      <h1><%= t('edit') %></h1>
      <%= render "form", company: @company %>
    </div>
    <div class="btn-group mt-3">
      <%= link_to companies_path, class: "btn btn-secondary", title: t('back') do %>
        <i class="bi bi-arrow-left-circle-fill"></i>
      <% end %>
    </div>
  </main>
</div>

app/views/companies/index.html.erb
<div class="row">
  <%= render 'homes/nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 my-4">
    <%= render 'layouts/breadcrumbs' %>
    <h1><%= t('all_list') %></h1>
    
    <div class="table-responsive" data-controller="datatables" data-datatables-language-value="<%= I18n.locale %>">
      <table class="table table-hover" data-datatables-target="table">
        <thead>
          <tr>
            <th scope="col"><%= Company.human_attribute_name(:name) %></th>
            <th scope="col"><%= Company.human_attribute_name(:updated_at) %></th>
            <th scope="col"><%= I18n.t('.members_count') %></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% if current_user&.admin? %>
            <%= render partial: 'company', collection: @companies, locals: { admin: true } %>
          <% else %>
            <%= render partial: 'company', collection: @user_companies, locals: { admin: false } %>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <% if current_user.admin? && can?(:create, Company) %>
      <div class="btn-group pt-3">
        <%= link_to t('new'), new_company_path, class: 'btn btn-sm btn-outline-primary' %>
      </div>
    <% end %>
  </main>
</div>

app/views/companies/new.html.erb
<div class="row">
  <%= render 'homes/nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 my-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="p-3">
      <h1><%= t('new') %></h1>
      <%= render "form", company: @company %>
    </div>
    <div class="btn-group mt-3">
      <%= link_to companies_path, class: "btn btn-secondary", title: t('back') do %>
        <i class="bi bi-arrow-left-circle-fill"></i>
      <% end %>
    </div>
  </main>
</div>

app/views/companies/show.html.erb
<div class="row">
  <%= render 'nav' %>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 my-4">
    <%= render 'layouts/breadcrumbs' %>
    <div class="m-3">
      <h1><%= @company.name %></h1>
      <% if current_user.admin? || @company.memberships.exists?(user: current_user, role: :owner) %>
        <div class="row g-4">
          <div class="col-6">
            <div class="p-3 rounded border">
              <div class="add-member">
                <h3><%= I18n.t('.add_member') %></h3>
                <%= form_with url: company_memberships_path(@company), local: true do |form| %>
                  <div class="mb-3">
                    <%= form.label :user_id, class: 'form-label' %>
                    <%= form.collection_select :user_id, User.all, :id, :email, { include_blank: true }, { class: 'form-select' } %>
                  </div>
                  <%= form.submit I18n.t('.add'), class: 'btn btn-sm btn-outline-primary' %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="p-3 rounded border">
              <% if current_user.admin? %>
                <div class="add-owner">
                  <h3><%= I18n.t('.add_owner') %></h3>
                  <%= form_with url: add_owner_company_memberships_path(@company), local: true do |form| %>
                    <div class="mb-3">
                      <%= form.label :user_id, class: 'form-label' %>
                      <%= form.collection_select :user_id, User.all, :id, :email, { include_blank: true }, { class: 'form-select' } %>
                    </div>
                    <%= form.submit I18n.t('.add'), class: 'btn btn-sm btn-outline-primary' %>
                  <% end %>
                </div>
              <% else %>
                <div class="add-owner">
                  <h3><%= I18n.t('.add_owner') %></h3>
                  <div class="text-center text-muted">
                    <i class="bi bi-lock" style="font-size: 2rem;"></i>
                    <p class="mt-3"><%= I18n.t('.only_admins_can_add_owners') %></p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row g-4 mt-2">
          <div class="col-12">
            <div class="p-3 rounded border">
              <h3><%= I18n.t('.members') %></h3>
              <div class="table-responsive" data-controller="datatables" data-datatables-language-value="<%= I18n.locale %>">
                <table class="table table-hover" data-datatables-target="table">
                  <thead>
                    <tr>
                      <th scope="col"><%= I18n.t('.email') %></th>
                      <th scope="col"><%= I18n.t('.actions') %></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @company.memberships.includes(:user).each do |membership| %>
                      <tr class="<%= 'table-primary' if membership.owner? %>" style="cursor: pointer;">
                        <td><%= membership.user.email %></td>
                        <td class="text-end">
                          <%= button_to company_membership_path(@company, membership),
                              method: :delete,
                              data: { turbo_confirm: t('are_you_sure') },
                              class: "btn btn-outline-danger #{'hidden' unless can?(:destroy, membership)}",
                              title: t('destroy') do %>
                            <i class="bi bi-trash3-fill"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="row g-4">
          <div class="col-12">
            <div class="p-3 rounded border">
              <h3><%= I18n.t('.members') %></h3>
              <div class="table-responsive" data-controller="datatables" data-datatables-language-value="<%= I18n.locale %>">
                <table class="table table-hover" data-datatables-target="table">
                  <thead>
                    <tr>
                      <th scope="col"><%= I18n.t('.email') %></th>
                      <th scope="col"><%= I18n.t('.actions') %></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @company.memberships.includes(:user).each do |membership| %>
                      <tr class="<%= 'table-primary' if membership.owner? %>">
                        <td><%= membership.user.email %></td>
                        <td class="text-end">
                          <%= button_to company_membership_path(@company, membership),
                              method: :delete,
                              data: { turbo_confirm: t('are_you_sure') },
                              class: "btn btn-outline-danger #{'hidden' unless can?(:destroy, membership)}",
                              title: t('destroy') do %>
                            <i class="bi bi-trash3-fill"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="btn-group mt-3">
      <% if can?(:destroy, @company) && can?(:update, @company) %>
        <%= button_to company_path(@company),
            method: :delete,
            data: { turbo_confirm: t('are_you_sure') },
            class: "btn btn-danger",
            title: t('destroy') do %>
          <i class="bi bi-trash3-fill"></i>
        <% end %>
        <%= link_to edit_company_path(@company), class: "btn btn-warning", title: t('edit') do %>
          <i class="bi bi-pencil-fill"></i>
        <% end %>
        <%= link_to companies_path, class: "btn btn-secondary", title: t('back') do %>
          <i class="bi bi-arrow-left-circle-fill"></i>
        <% end %>
      <% else %>
        <%= link_to companies_path, class: "btn btn-secondary", title: t('back') do %>
          <i class="bi bi-arrow-left-circle-fill"></i>
        <% end %>
      <% end %>
    </div>
  </main>
</div>