config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "homes#index"

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :templates do
    member do
      post :sample_template
      post :upload_image
    end

    collection do
      post :sample_template
      post :upload_image
    end
  end

  resources :companies do
    resources :memberships, only: [:create, :destroy] do
      collection do
        post :add_owner
      end
    end

    resources :projects do
      post :sample_document, on: :member

      resources :documents do
        member do
          get  :document_images
          post :upload_image
        end

        collection do
          post :create_from_template
        end
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  authenticate :user, lambda { |u| u.admin? || u.email == 'web.dev.adk@gmail.com' } do
    mount PgHero::Engine, at: "pghero"
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    six_months_ago ||= Date.today - 6.months
    @users_by_month ||= User.where("last_sign_in_at >= ?", six_months_ago)
                          .group_by_month(:last_sign_in_at, last: 6)
                          .count

    @latest_trunsactions_documents ||= Document.where(
      user_id: current_user.id
    ).or(
      Document.where(company_id: current_user.company_ids)
    ).order(created_at: :desc)
    .limit(7)

    @templates ||= Template.last(4)

    @breadcrumbs ||= [
      { name: "<i class='bi bi-house'></i> #{I18n.t('.dashboard')}".html_safe, url: root_path, current: true }
    ]
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/shared/_nav.html.erb
<nav id="sidebar" class="data-bs-theme col-md-3 col-lg-2 d-md-block sidebar collapse">
    <div class="position-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link active", aria: { current: "page" }, data: { turbo_frame: "right-panel" } do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                  <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                  <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
                <span class="ms-2"><%= I18n.t('.dashboard') %></span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to templates_path, class: "nav-link", data: { turbo_frame: "right-panel" } do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file">
                  <path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path>
                  <polyline points="13 2 13 9 20 9"></polyline>
                </svg>
                <span class="ms-2"><%= I18n.t('.templates') %></span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to documents_path, class: "nav-link", data: { turbo_frame: "right-panel" } do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers">
                  <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
                  <polyline points="2 17 12 22 22 17"></polyline>
                  <polyline points="2 12 12 17 22 12"></polyline>
                </svg>
                <span class="ms-2"><%= I18n.t('.documents') %></span>
              <% end %>
            </li>
            <hr>
            <li class="nav-item">
              <%= link_to companies_path, class: "nav-link", data: { turbo_frame: "right-panel" } do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users">
                  <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                  <circle cx="9" cy="7" r="4"></circle>
                  <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                  <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                </svg>
                <span class="ms-2"><%= I18n.t('.companies') %></span>
              <% end %>
            </li>
            <hr>
            <li class="nav-item">
              <%= link_to "#", class: "btn btn-sm btn-secondary ms-3 mt-2" do %>
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-book" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M1 2.828v9.923c.918-.35 2.107-.692 3.287-.81 1.094-.111 2.278-.039 3.213.492V2.687c-.654-.689-1.782-.886-3.112-.752-1.234.124-2.503.523-3.388.893zm7.5-.141v9.746c.935-.53 2.12-.603 3.213-.493 1.18.12 2.37.461 3.287.811V2.828c-.885-.37-2.154-.769-3.388-.893-1.33-.134-2.458.063-3.112.752zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                </svg>
                <span class="ms-2"><%= t('.read_tutorial') %></span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "#", class: "btn btn-sm btn-warning ms-3 mt-2" do %>
                ⚡︎ <%= t('.volt_qna') %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "#", class: "btn btn-sm btn-primary ms-3 mt-2" do %>
                <%= t('.coffee_chat') %> ☕
              <% end %>
            </li>
          </ul>
    </div>
</nav>

app/views/homes/shared/_reserved.html.erb
<div class="row">
    <div class="col-12 col-xl-8 mb-4 mb-lg-0">
        <div class="card">
            <h5 class="card-header">Последние транзакции</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Order</th>
                            <th scope="col">Product</th>
                            <th scope="col">Customer</th>
                            <th scope="col">Total</th>
                            <th scope="col">Date</th>
                            <th scope="col"></th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @latest_trunsactions_documents.each do |document| %>
                            <tr>
                              <th scope="row"><%= document.id %></th>
                              <td><%= document.title %></td>
                              <td><%= document.user.email %></td>
                              <td><%= document.company.memberships.count %></td>
                              <td><%= document.created_at %></td>
                              <td><%= link_to t('.show'), document_path(document), class: 'btn btn-sm btn-primary' %></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                </div>
                <div class="d-grid">
                  <%= link_to t('all_list'), documents_path, class: 'btn btn-light' %>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-xl-4">
        <div class="card">
            <h5 class="card-header">Трафик за последние 6 мес.</h5>
            <div class="card-body">
              <div data-controller="chart"
                   data-chart-labels='<%= @users_by_month.keys.map { |date| date.strftime("%B %Y") } %>'
                   data-chart-data='<%= @users_by_month.values %>'>
                <canvas data-chart-target="canvas"></canvas>
              </div>
            </div>
        </div>
    </div>
</div>